apiVersion: v1
kind: Namespace
metadata:
  name: realwf

---

apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: realwf
  name: sauser

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  namespace: realwf
  name: workflows-role
rules:
  - apiGroups: [""]
    resources: ["pods","pods/status","pods/log","pods/exec","nodes","bindings","configmaps"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  namespace: realwf
  name: workflows-rolebind
roleRef:
  kind: ClusterRole
  name: workflows-role
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: sauser
    namespace: realwf


