
run:
	nextflow run main.nf

run-cws:
	nextflow run main.nf -c ../../config/base.config -c ../../config/localcws.config -c ../../config/default.config

clean:
	${RM} -r work
	${RM} -r .nextflow*
	${RM} trace*
	${RM} Task*

