apiVersion: v1
kind: PersistentVolume
metadata:
  name: workflows-hostpath-pv
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 1Gi
  hostPath:
    path: "/workflows"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: workflows
  name: workflows-hostpath-pvc
spec:
  volumeName: workflows-hostpath-pv
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi

