apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-hostpath-pv
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 10Gi
  hostPath:
    path: "/nfs"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: workflows
  name: nfs-hostpath-pvc
spec:
  volumeName: nfs-hostpath-pv
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
